name: release

on: 
  push:
    branches:
      - v0.2.0.0

jobs:
  release-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Update brew and install Xolentum dependencies
      run: brew update && brew install boost hidapi zmq libpgm miniupnpc ldns expat libunwind-headers protobuf
    - name: Build
      run: USE_SINGLE_DIR=1 make release-static  -j3
    - name: Upload Mac artifacts
      uses: actions/upload-artifact@master
      with:
        name: MacOS
        path: 'build/**/**/**/bin/xolentum*'


  release-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: eine/setup-msys2@v0
      with:
        update: true
    - name: Install Xolentum dependencies
      run: msys2do pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb git
    - name: Build
      run: msys2do USE_SINGLE_DIR=1 make release-static-win64 -j2
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@master
      with:
        name: Windows
        path: 'build/**/**/**/bin/xolentum*'

  release-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: Set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: Update apt
      run: sudo apt update
    - name: Install Xolentum dependencies
      run: sudo apt-get install xz-utils g++ libtool-bin autoconf automake build-essential cmake pkg-config pcsc-tools pcscd libpcsclite1 libudev-dev libhidapi-dev libzmq3-dev libunbound-dev libboost-all-dev libusb-1.0-0-dev libusb-dev libssl-dev libsodium-dev libcurl4-openssl-dev libminiupnpc-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev libgtest-dev doxygen graphviz libhidapi-libusb0 libnorm-dev libpgm-dev
    - name: Build
      run: USE_SINGLE_DIR=1 make release-static -j3
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: Linux
        path: 'build/**/**/**/bin/xolentum*'
